name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo usermod -a -G microk8s $USER
          newgrp microk8s <<EOF
          microk8s status --wait-ready
          microk8s enable dns storage
          EOF
        shell: bash
      
      - name: Enable DNS and storage
        run: |
          microk8s enable dns storage

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run frontend tests
        run: |
         cd frontend
          npm install
          npm test

      - name: Run backend tests
        run: |
          cd backend
          npm install
          npm test

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USER }}/backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USER }}/frontend:latest
        
      - name: Deploy to Kubernetes using MicroK8s
        run: |
          microk8s kubectl apply -f k8s/mongo-deployment.yml
          microk8s kubectl apply -f k8s/backend-deployment.yml
          microk8s kubectl apply -f k8s/frontend-deployment.yml
